// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "dev.antoinechalifour.mattermost-plugin-threads",
    "name": "Threads Plugins",
    "description": "This plugin hides threads from the main posts list.",
    "version": "0.1.1",
    "min_server_version": "5.12.0",
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": []
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
